### PR TITLE
fix: add the ability to pass an array of files to append to formData

### PR DESCRIPTION
**Pull request by mosijava**
We have a use case where we want to pass multiple files simultaneously to an API. We should pass the files as an array, which is impossible because the code expects a single file.

### CODE REVIEW

**Review by KnisterPeter — CHANGES_REQUESTED** [review]
@mosijava Sorry for the late reply, didn't saw your request.
Can you add a test case for this feature?

**Comment by mosijava** [comment]
@KnisterPeter I will, but I have to find a time for that. I will let you know

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
@mosijava Released as version 4

**Pull request merged**
